[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm --prefix simple-backend install']

[phases.build]
cmds = ['echo "No build required"']

[start]
cmd = 'node simple-backend/index.js' 