[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['cd simple-backend && npm install']

[phases.build]
cmds = ['echo "No build required"']

[start]
cmd = 'cd simple-backend && npm start' 